name : MERN CI/CD

on: 
  push:
     branches:
        -main

jobs:
   build:
   runs-on: ubuntu-latest

    steps:

      - name:Checkout code
        uses:actions/checkout@v2


      -name:Setup Node.js
       uses: actions/setup-node@v2
       with:
        node-version:"18"

      -name:Install backend dependencies
       working-directory: ./backend
       run : npm install

       -name: backend tests (optional)
        working-directory: ./backend
        run:npm test || echo "NO backend tests found"

        -name:Install frontend dependencies
        working-directory: ./frontend
        run :npm install

        -name:Build frontend
        working-directory : ./frontend
        run:npm run build
        
